---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: docker-private-registry
  name: docker-private-registry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-private-registry
  template:
    metadata:
      labels:
        app: docker-private-registry
    spec:
      containers:
      - image: registry:2
        imagePullPolicy: IfNotPresent
        name: docker-private-registry
        env:
        - name: REGISTRY_HTTP_ADDR
          value: 0.0.0.0:5000
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/cert.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/cert.key
        ports:
        - containerPort: 5000
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/registry
          name: image-store
        - mountPath: /certs
          name: certs
      volumes:
      - emptyDir: {} # THIS IS NOT PERSISTENT! WILL DELETE WITH POD!
        name: image-store
      - name: certs
        secret:
          secretName: registry-tls
          items:
          - key: tls.crt
            path: cert.crt
            mode: 256 # 0400 in decimal
          - key: tls.key
            path: cert.key
            mode: 256 # 0400 in decimal
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: docker-private-registry
  name: docker-private-registry
spec:
  ports:
  - nodePort: 30500
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: docker-private-registry
  type: NodePort

---
apiVersion: v1
kind: Secret
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVERENDQXZTZ0F3SUJBZ0lVVGFQTmgzdytTQTQ5UFpLZ3VkeUVKWFNpK0Vrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2NERUxNQWtHQTFVRUJoTUNWVk14RlRBVEJnTlZCQWdUREZCbGJtNXplV3gyWVc1cFlURVRNQkVHQTFVRQpCeE1LU0dGeWNtbHpZblZ5WnpFVE1CRUdBMVVFQ2hNS1MzVmlaWEp1WlhSbGN6RUxNQWtHQTFVRUN4TUNRMEV4CkV6QVJCZ05WQkFNVENrdDFZbVZ5Ym1WMFpYTXdIaGNOTWpBd01qSTBNakF6TXpBd1doY05NakV3TWpJek1qQXoKTXpBd1dqQnhNUXN3Q1FZRFZRUUdFd0pWVXpFVk1CTUdBMVVFQ0JNTVVHVnVibk41YkhaaGJtbGhNUk13RVFZRApWUVFIRXdwSVlYSnlhWE5pZFhKbk1STXdFUVlEVlFRS0V3cExkV0psY201bGRHVnpNU0V3SHdZRFZRUUxFeGhMCmRXSmxjbTVsZEdWeklGUm9aU0JCYkhSaE15QlhZWGt3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUMvczRPSWpXUnNEeE5hclh6RGhhbWRVdGNHUHBiL3J1RDhHU0dVWlBabmdQL1hQR2p5Vkc2SwpDeFlBWFBXWTQ4ZmYzU045cUROL3BUYUt3Q0hrY0NyeWxZNlV0Ujk2Ty9FTERjeTFtR1lIMmowcyt2QlBOUlpNCjlwOVdtQXdFRUVzUkdqbm9rb0ZFRjc1UTVDclp3R1J2MWk1cUVJeFlNOTQvaDVzT1FWdEFxTzJDT1QrR0FpdzYKa1BHZ2lTUDU0Y0xhdithS3ZGYnJYMStIVEthN2VDYXdQK2dOc2JIblorcTd1ejE3eThhOTM4aXNteTlndTcrZAphQU52bHdZRko3d1ZsSG9xaFJVS21kYWtqNnU1ZVp5VFVlQmo5S0FGYW9HUDEzcmZCMnVzbEVmVjJXdzlVTmh6CmhSOFpBS3dUYWthWXQ5TVZLeHpXa3A2YUhORGJEKzg1QWdNQkFBR2pnWnd3Z1prd0RnWURWUjBQQVFIL0JBUUQKQWdXZ01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQQpNQjBHQTFVZERnUVdCQlRlRm1weXZpeTkwTWpwMUJMMTlGeWNLaFErSERBZkJnTlZIU01FR0RBV2dCUnpjeGxCCng4bUtYNXAwL2RwQm5pa3grYnlkUlRBYUJnTlZIUkVFRXpBUmdnbHNiMk5oYkdodmMzU0hCSDhBQUFFd0RRWUoKS29aSWh2Y05BUUVMQlFBRGdnRUJBRHZ2bTdvbUFreWdmSXJYOVhwZzk0WUJ5UDNlQW5XTXJHZHd3ZzVyd21aNwpzYVBkaE5yV0ZPbklNdmVxS0JhNm1lZXBidFNXVkQ1dDloRWpRRXRuVFFuczJwaFB3cnRjczFGUzRNQ1lXZ1VlCm0wOU95MXpPekIvZHNnbis3OXVkZllzdGxhOU1UWitSaWpQdkJhODZpL0hDNzZEZ2dESk5kZkdIZzkweksvbmsKekxpOEZRaGxPak53WDdzL2pwdFFNczdURCswbXdBalJBbDlNTVk2czczMWJ4T3dTMVkwdW90OHFQejRPait1VgphQkF0ZFV1a242SW5WendzLzc1c3c4N0tEa1kweXlNRWplMFJYMVhCN2lDL2FGaXBIUFh4YmErbGJsTnV5b1Q4Ck5mM0VONmxhS3U4bUFpYXduK1dUK0lLc1hiSmJYS1IxYkNQU1VmTUxYOW89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K 
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBdjdPRGlJMWtiQThUV3ExOHc0V3BuVkxYQmo2Vy82N2cvQmtobEdUMlo0RC8xenhvCjhsUnVpZ3NXQUZ6MW1PUEgzOTBqZmFnemY2VTJpc0FoNUhBcThwV09sTFVmZWp2eEN3M010WmhtQjlvOUxQcncKVHpVV1RQYWZWcGdNQkJCTEVSbzU2SktCUkJlK1VPUXEyY0JrYjlZdWFoQ01XRFBlUDRlYkRrRmJRS2p0Z2prLwpoZ0lzT3BEeG9Ja2orZUhDMnIvbWlyeFc2MTlmaDB5bXUzZ21zRC9vRGJHeDUyZnF1N3M5ZTh2R3ZkL0lySnN2CllMdS9uV2dEYjVjR0JTZThGWlI2S29VVkNwbldwSStydVhtY2sxSGdZL1NnQldxQmo5ZDYzd2RyckpSSDFkbHMKUFZEWWM0VWZHUUNzRTJwR21MZlRGU3NjMXBLZW1oelEydy92T1FJREFRQUJBb0lCQUZYL1dncHdJNVMyVHFCbgpJNGt5OVJ3MmhXK3Z0RjJQUGk3WnQwNnkzRGNpajZNbTNvMlhndDg2aWV3dng1MkcwYXVEc09BMkRLUStvWEV0Ck1BY2lxcUdZcGhYZ0N2YnkzUGR3Z1YwVnVPL2MzNFRHTGZmYWdONlY1SFVjVUllaUo0ck1rUjNjVzFFSXRiL2sKRzdVRHNnclpzb2l5VThOZHdWNE9uMmlOdVRvUHhucmxJK2FMNkZ5QWhVUXV3WTVhTnkwY0pZZzM1cGlidVRhNwpIcGQ0K0R5TTl2VytrZngvTHdzOEc0bzhyZWhOTHRocXVBR3kwWUNMZ0dCQjFMT1FFQW5SZ1ZtQm5TdUZKTnZKCkd0YXFaT0twa1FKcnV2aS9uRjNDUzUzTDFRUEdqSFBmSHBxVE9UR2NPcVFvY01YdkhocWJrNjdtS0JVRCtYK1UKWTllOTFtRUNnWUVBeUc1MmNLWWxlS1B5Y0Rjait2T01iWndsTTZjcTdUcGU2K0l5SGNJMnZ5ZW9MeFh0TVlZbQpKTWt5Q2tnSXE4ejc5UEJaR1IrSER6a3JtMzNVR1UrT0R4YTdKWDNmVzBac0ErbDBubitoUXdldWJiMWJhcXJICnNwclpxQWV2c3laMmF2RW1pVTZCR3ZVUFpRVFJodjk0VFhsYlBENzNhWGlnL1ptb0FORE1ZSU1DZ1lFQTlObHMKbEdYUjJCWW9vQ2tRWjJVL00rSWpBQWk0Rlp1R3ZYYUllMHc1WldWTXF4VDZBS3FyRVhBSkd5OFh6M1M2cW1EWgp6V3Z6enMyNklsSktjSWROL21sWWJyTnl2d1FKZFJtVkNiNjE2Q295b3ZYQ3JjSEhuU3hRSmtyN215Ri9MUHNxCjlXRENWU3ZMeWhqazZnVS9lQ3JGY1RMbk9SWVcxeGkzWUxBS0xKTUNnWUJnTDdyQlJzcTJ3WjhJUVQ0UUlhOGoKcndxZlpqc1FpN0dmNi9aM0Y0d2tZa2l4Q0FuRGVZaDJvT05WMGNudmdManRqQ2FHQ3Y1S3pQbmpiaGhLYVVaWQpjV1V3a2Q2TnRCY0VMWlljdGsxU21LNFoxZ1M0Qk9zL0NGY3A3ejVmY0RibURZS2I1RVBMQnczelFjTzMwSVFRClVndjV0cElQV0tlUjdKcVdnWjJETndLQmdFLy9DWDZpbGFEbi9IWDNkS2lUWjhibngwK25pWjFscHV3WDRoZUcKbStvSTRyZXlyc3V3OXh0SFkzSkNQS0ZISGdXMGh2U2FwSm1ZbFl2Skh4RU00K3FQT0psU2Y5Yncxcll2bVlZSgpqUjFCVERINTRaVXJqckJIWGhoa3Z6ZThCZlVJU3N6SXhEVlhqY21Gd0tURStpdWtyY1dDUUJGaXFpdTBvNVV2CmJ1T0pBb0dBR0pVMDlaczZUWEt3dVlVTklZOUJjZzFtdHpESkhET2IwaDNaelErMnJla1I5NnRyWjZ2VFBoOEQKZUJNYUZFbStjaWxKaFI5QTVwSDNZTElnMmZMbU5Ob25wbi8wUDk1TzhNNVZLOVVRMnJPR3lsZHdoZ25wekNLSQpkMG5lT0dJSU9JTTRZTWRWd21CRDZRQVJGcEdOODlVQkQzUlhxcHFDbzBlZmVuTXZoKzQ9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
metadata:
  name: registry-tls
  namespace: default
type: Opaque
