apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"what":"what"},"name":"nginx","namespace":"default"},"spec":{"containers":[{"image":"nginx:1.7.9","name":"nginx","ports":[{"containerPort":80}]}]}}
  creationTimestamp: "2020-02-26T23:46:40Z"
  labels:
    app: web_service
    what: what
    importance: critical
    customer: internal_use
  name: nginx
  namespace: default
  resourceVersion: "305666"
  selfLink: /api/v1/namespaces/default/pods/nginx
  uid: 8535d509-0431-4455-bde8-3547ecbd0cc1
spec:
  containers:
  - image: nginx:1.7.9
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-m5vsm
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-1519-node-03
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-m5vsm
    secret:
      defaultMode: 420
      secretName: default-token-m5vsm
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-02-26T23:46:40Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-02-26T23:46:57Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-02-26T23:46:57Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-02-26T23:46:40Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://0d466a32fd9e1ac89f20cc449a2d5a607bb26af29479dee37d5e1a0987f90f3f
    image: docker.io/library/nginx:1.7.9
    imageID: sha256:35d28df486f6150fa3174367499d1eb01f22f5a410afe4b9581ac0e0e58b3eaf
    lastState:
      terminated:
        containerID: containerd://0bed7bedb6a5f2ddb290cda7f76755079b06bb1cdb87d8c717bd3044de9d9953
        exitCode: 0
        finishedAt: "2020-02-26T23:46:56Z"
        reason: Completed
        startedAt: "2020-02-26T23:46:42Z"
    name: nginx
    ready: true
    restartCount: 1
    state:
      running:
        startedAt: "2020-02-26T23:46:56Z"
  hostIP: 10.10.102.101
  phase: Running
  podIP: 192.168.138.176
  qosClass: BestEffort
  startTime: "2020-02-26T23:46:40Z"
